# -*- coding: utf-8 -*-
"""Precios_cierre.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O-NElF6Zovvfg5lWmUDm05kgUg9jQpPi
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import datetime as dt

st.image("UNRC.png", caption="Universidad Nacional Rosario Castellanos", width=300)

# --- Configuración de la página ---
st.set_page_config(page_title="Precio de Cierre Mensual", page_icon="", layout="centered")

# --- Título e instrucciones ---
st.title(" Precio de Cierre - Último Día Hábil de Cada Mes")

st.markdown("""
Esta aplicación obtiene el **precio de cierre del último día hábil de cada mes** 
de los últimos **5 años**, usando datos de **Yahoo Finance**.

-Ejemplos de claves de pizarra:
- `AMXL.MX` → América Móvil  
- `CEMEXCPO.MX` → Cemex  
""")

# --- Entrada del usuario ---
ticker = st.text_input("🔎 Ingresa la clave de pizarra:", value="AMXL.MX")

# --- Rango de fechas (últimos 5 años) ---
end = dt.date.today()
start = end - dt.timedelta(days=5 * 365)

if ticker:
    try:
        # Descargar datos diarios
        df = yf.download(ticker, start=start, end=end)

        if not df.empty:
            # Obtener último día hábil de cada mes
            df_monthly = df.resample('M').last()

            # Limpiar DataFrame
            df_monthly = df_monthly[['Close']].dropna()
            df_monthly.index = df_monthly.index.strftime("%Y-%m-%d")

            # Asegurar que el último valor sea escalar
            last_close = float(df_monthly["Close"].iloc[-1])
            last_date = df_monthly.index[-1]

            # Mostrar resultados
            st.success(f"**Último día hábil mensual:** {last_date}")
            st.metric(label="💵 Precio de cierre más reciente", value=f"${last_close:,.2f}")

            # Mostrar gráfico mensual
            st.line_chart(df_monthly["Close"], use_container_width=True)

            # Mostrar tabla de datos mensuales
            with st.expander("📅 Ver datos mensuales"):
                st.dataframe(df_monthly.tail(12))

            # --- Generar CSV para descarga ---
            csv = df_monthly.to_csv().encode("utf-8")

            st.download_button(
                label="⬇️ Descargar datos mensuales en CSV",
                data=csv,
                file_name=f"{ticker}_cierres_mensuales.csv",
                mime="text/csv"
            )
        else:
            st.warning("No se encontraron datos para la clave de pizarra ingresada.")
    except Exception as e:
        st.error(f"Ocurrió un error: {e}")
